CREATE TABLE ARTISTA (
 ID_Artista NUMERIC(15) NOT NULL,
 Nome VARCHAR(50)
);

ALTER TABLE ARTISTA ADD CONSTRAINT PK_ARTISTA PRIMARY KEY (ID_Artista);


CREATE TABLE BANDA (
 ID_Banda NUMERIC(15) NOT NULL,
 Quantidade_membros VARCHAR(2),
 ID_Artista NUMERIC(15) NOT NULL
);

ALTER TABLE BANDA ADD CONSTRAINT PK_BANDA PRIMARY KEY (ID_Banda);


CREATE TABLE EVENTO (
 ID_Evento NUMERIC(15) NOT NULL,
 Nome VARCHAR(50),
 Data_início DATE,
 Data_término DATE
);

ALTER TABLE EVENTO ADD CONSTRAINT PK_EVENTO PRIMARY KEY (ID_Evento);


CREATE TABLE LOCAL (
 ID_Local NUMERIC(15) NOT NULL,
 Nome VARCHAR(50),
 Capacidade NUMERIC(15),
 Rua VARCHAR(50),
 Número NUMERIC(15),
 Complemento VARCHAR(50),
 Cidade VARCHAR(50),
 Estado VARCHAR(50),
 CEP NUMERIC(8)
);

ALTER TABLE LOCAL ADD CONSTRAINT PK_LOCAL PRIMARY KEY (ID_Local);


CREATE TABLE LOCAL_EVENTO (
 ID_Evento NUMERIC(15) NOT NULL,
 ID_Local NUMERIC(15) NOT NULL
);

ALTER TABLE LOCAL_EVENTO ADD CONSTRAINT PK_LOCAL_EVENTO PRIMARY KEY (ID_Evento,ID_Local);


CREATE TABLE MÚSICO (
 ID_Músico VARCHAR(15) NOT NULL,
 Data_nascimento DATE,
 Cidade_nascimento VARCHAR(50),
 País_nascimento VARCHAR(50),
 ID_Artista NUMERIC(15) NOT NULL
);

ALTER TABLE MÚSICO ADD CONSTRAINT PK_MÚSICO PRIMARY KEY (ID_Músico);


CREATE TABLE SHOW (
 ID_Evento NUMERIC(15) NOT NULL,
 ID_Artista NUMERIC(15) NOT NULL,
 Hora_início TIME(10),
 Hora_término TIME(10)
);

ALTER TABLE SHOW ADD CONSTRAINT PK_SHOW PRIMARY KEY (ID_Evento,ID_Artista);


CREATE TABLE TELEFONE (
 Número_telefone NUMERIC(9) NOT NULL,
 Código_área NUMERIC(2),
 Descrição VARCHAR(100)
);

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE PRIMARY KEY (Número_telefone);


CREATE TABLE USUÁRIO (
 EMAIL_Usuário VARCHAR(50) NOT NULL,
 Número_telefone NUMERIC(9) NOT NULL,
 Nome VARCHAR(50),
 Senha VARCHAR(50)
);

ALTER TABLE USUÁRIO ADD CONSTRAINT PK_USUÁRIO PRIMARY KEY (EMAIL_Usuário,Número_telefone);


CREATE TABLE ZONA (
 ID_Zona NUMERIC(15) NOT NULL,
 Nome VARCHAR(50),
 Localização VARCHAR(50),
 Capacidade NUMERIC(10)
);

ALTER TABLE ZONA ADD CONSTRAINT PK_ZONA PRIMARY KEY (ID_Zona);


CREATE TABLE ZONA_LOCAL (
 ID_Local NUMERIC(15) NOT NULL,
 ID_Zona NUMERIC(15) NOT NULL
);

ALTER TABLE ZONA_LOCAL ADD CONSTRAINT PK_ZONA_LOCAL PRIMARY KEY (ID_Local,ID_Zona);


CREATE TABLE BANDA_MÚSICO (
 ID_Banda NUMERIC(15) NOT NULL,
 ID_Músico VARCHAR(15) NOT NULL,
 Ano_ingresso NUMERIC(4),
 Ano_saída NUMERIC(4)
);

ALTER TABLE BANDA_MÚSICO ADD CONSTRAINT PK_BANDA_MÚSICO PRIMARY KEY (ID_Banda,ID_Músico);


CREATE TABLE LOTE_INGRESSOS (
 ID_Zona NUMERIC(15) NOT NULL,
 ID_Lote CHAR(10) NOT NULL,
 ID_Evento NUMERIC(15) NOT NULL,
 ID_Local NUMERIC(15) NOT NULL,
 Nome VARCHAR(50),
 Preço NUMERIC(10),
 Início_vendas DATE
);

ALTER TABLE LOTE_INGRESSOS ADD CONSTRAINT PK_LOTE_INGRESSOS PRIMARY KEY (ID_Zona,ID_Lote,ID_Evento,ID_Local);


CREATE TABLE INGRESSO (
 ID_Ingresso VARCHAR(15) NOT NULL,
 Número_assento NUMERIC(5),
 ID_Zona NUMERIC(15) NOT NULL,
 ID_Lote CHAR(10) NOT NULL,
 ID_Evento NUMERIC(15) NOT NULL,
 ID_Local NUMERIC(15) NOT NULL
);

ALTER TABLE INGRESSO ADD CONSTRAINT PK_INGRESSO PRIMARY KEY (ID_Ingresso);


CREATE TABLE COMPRA (
 EMAIL_Usuário VARCHAR(50) NOT NULL,
 Número_telefone NUMERIC(9) NOT NULL,
 Data_aquisição DATE,
 ID_Ingresso VARCHAR(15)
);

ALTER TABLE COMPRA ADD CONSTRAINT PK_COMPRA PRIMARY KEY (EMAIL_Usuário,Número_telefone);


ALTER TABLE BANDA ADD CONSTRAINT FK_BANDA_0 FOREIGN KEY (ID_Artista) REFERENCES ARTISTA (ID_Artista);


ALTER TABLE LOCAL_EVENTO ADD CONSTRAINT FK_LOCAL_EVENTO_0 FOREIGN KEY (ID_Evento) REFERENCES EVENTO (ID_Evento);
ALTER TABLE LOCAL_EVENTO ADD CONSTRAINT FK_LOCAL_EVENTO_1 FOREIGN KEY (ID_Local) REFERENCES LOCAL (ID_Local);


ALTER TABLE MÚSICO ADD CONSTRAINT FK_MÚSICO_0 FOREIGN KEY (ID_Artista) REFERENCES ARTISTA (ID_Artista);


ALTER TABLE SHOW ADD CONSTRAINT FK_SHOW_0 FOREIGN KEY (ID_Evento) REFERENCES EVENTO (ID_Evento);
ALTER TABLE SHOW ADD CONSTRAINT FK_SHOW_1 FOREIGN KEY (ID_Artista) REFERENCES ARTISTA (ID_Artista);


ALTER TABLE USUÁRIO ADD CONSTRAINT FK_USUÁRIO_0 FOREIGN KEY (Número_telefone) REFERENCES TELEFONE (Número_telefone);


ALTER TABLE ZONA_LOCAL ADD CONSTRAINT FK_ZONA_LOCAL_0 FOREIGN KEY (ID_Local) REFERENCES LOCAL (ID_Local);
ALTER TABLE ZONA_LOCAL ADD CONSTRAINT FK_ZONA_LOCAL_1 FOREIGN KEY (ID_Zona) REFERENCES ZONA (ID_Zona);


ALTER TABLE BANDA_MÚSICO ADD CONSTRAINT FK_BANDA_MÚSICO_0 FOREIGN KEY (ID_Banda) REFERENCES BANDA (ID_Banda);
ALTER TABLE BANDA_MÚSICO ADD CONSTRAINT FK_BANDA_MÚSICO_1 FOREIGN KEY (ID_Músico) REFERENCES MÚSICO (ID_Músico);


ALTER TABLE LOTE_INGRESSOS ADD CONSTRAINT FK_LOTE_INGRESSOS_0 FOREIGN KEY (ID_Zona) REFERENCES ZONA (ID_Zona);
ALTER TABLE LOTE_INGRESSOS ADD CONSTRAINT FK_LOTE_INGRESSOS_1 FOREIGN KEY (ID_Evento,ID_Local) REFERENCES LOCAL_EVENTO (ID_Evento,ID_Local);


ALTER TABLE INGRESSO ADD CONSTRAINT FK_INGRESSO_0 FOREIGN KEY (ID_Zona,ID_Lote,ID_Evento,ID_Local) REFERENCES LOTE_INGRESSOS (ID_Zona,ID_Lote,ID_Evento,ID_Local);


ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_0 FOREIGN KEY (EMAIL_Usuário,Número_telefone) REFERENCES USUÁRIO (EMAIL_Usuário,Número_telefone);
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_1 FOREIGN KEY (ID_Ingresso) REFERENCES INGRESSO (ID_Ingresso);


